// 12 Seeded Products — AquaLux Bath & Sanitary

export const PRODUCTS = [
  {
    id: 1,
    name: "Freestanding Bathtub",
    brand: "AquaLux Pro",
    sku: "ALX-BTH-001",
    category: "Bathtubs",
    price: 45000,
    discountPrice: 42000,
    stock: 8,
    rating: 4.8,
    reviewCount: 124,
    status: "active",
    image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=600&q=80",
    ],
    description: "Transform your bathroom into a private spa with our exquisite freestanding bathtub. Crafted from premium acrylic with a glossy white finish, this centerpiece bathtub offers a deep soaking experience for ultimate relaxation. The freestanding design makes a bold architectural statement while the ergonomic shape conforms to the natural contours of the body.",
    specifications: {
      "Material": "Premium Acrylic",
      "Dimensions": "170 × 75 × 60 cm",
      "Weight": "48 kg",
      "Capacity": "280 litres",
      "Drain Position": "Center",
      "Finish": "Glossy White",
      "Warranty": "5 Years",
      "Installation": "Freestanding",
    },
    features: ["Deep soak design", "Slip-resistant base", "Drain included", "UV resistant finish"],
    isBestSeller: true,
    isFeatured: true,
    reviews: [
      { id: 1, user: "Priya Sharma", rating: 5, date: "2024-12-15", comment: "Absolutely stunning bathtub! The quality is premium and it completely transformed our bathroom. Worth every rupee." },
      { id: 2, user: "Rahul Mehta", rating: 5, date: "2024-11-28", comment: "Excellent craftsmanship. Easy installation and the finish is flawless. Highly recommend." },
      { id: 3, user: "Anita Kapoor", rating: 4, date: "2024-11-10", comment: "Beautiful design and good quality. Delivery was prompt and well-packaged." },
    ]
  },
  {
    id: 2,
    name: "Rain Shower Set",
    brand: "AquaFlow",
    sku: "ALX-SHW-001",
    category: "Showers",
    price: 12500,
    discountPrice: 10800,
    stock: 24,
    rating: 4.6,
    reviewCount: 89,
    status: "active",
    image: "https://images.unsplash.com/photo-1600566752734-2a0cd6af9176?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1600566752734-2a0cd6af9176?w=600&q=80",
      "https://images.unsplash.com/photo-1620626011761-996317702782?w=600&q=80",
    ],
    description: "Experience the sensation of standing under a warm summer rain with our premium Rain Shower Set. Featuring a large 300mm overhead shower head and an adjustable arm, this set delivers a gentle, enveloping rainfall effect that turns every shower into a luxurious ritual.",
    specifications: {
      "Head Size": "300mm × 300mm",
      "Material": "Stainless Steel 304",
      "Finish": "Brushed Nickel",
      "Water Pressure": "Low-Medium",
      "Installation": "Ceiling/Wall Mount",
      "Flow Rate": "12 L/min",
      "Warranty": "3 Years",
      "Includes": "Overhead + Hand shower",
    },
    features: ["300mm rain head", "360° adjustable arm", "Anti-limescale nozzles", "Handheld shower included"],
    isBestSeller: true,
    isFeatured: true,
    reviews: [
      { id: 1, user: "Vikram Singh", rating: 5, date: "2024-12-20", comment: "The rainfall effect is amazing. Best shower upgrade I've made!" },
      { id: 2, user: "Meera Nair", rating: 4, date: "2024-12-01", comment: "Good quality, easy to install. The water pressure is great." },
    ]
  },
  {
    id: 3,
    name: "Wall-Hung Toilet",
    brand: "CleanLine",
    sku: "ALX-TOI-001",
    category: "Toilets",
    price: 18000,
    discountPrice: 15500,
    stock: 15,
    rating: 4.7,
    reviewCount: 67,
    status: "active",
    image: "https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1564540586988-aa4e53c3d799?w=600&q=80",
    ],
    description: "Our wall-hung toilet combines sleek modern aesthetics with superior hygiene standards. The rimless design ensures effortless cleaning while the concealed cistern keeps your bathroom looking uncluttered and sophisticated. Dual-flush technology saves water without compromising performance.",
    specifications: {
      "Material": "Vitreous China",
      "Mounting": "Wall-hung",
      "Flush Volume": "3/6 litres (dual)",
      "Trap Way": "Concealed S-trap",
      "Seat": "Soft-close included",
      "Color": "Arctic White",
      "Warranty": "5 Years",
      "Certification": "BIS Certified",
    },
    features: ["Rimless bowl", "Dual-flush", "Soft-close seat", "Concealed cistern compatible"],
    isBestSeller: true,
    isFeatured: false,
    reviews: [
      { id: 1, user: "Arjun Patel", rating: 5, date: "2024-12-10", comment: "Sleek design and very hygienic. The rimless design makes cleaning a breeze." },
    ]
  },
  {
    id: 4,
    name: "Pedestal Wash Basin",
    brand: "AquaLux Pro",
    sku: "ALX-WBN-001",
    category: "Washbasins",
    price: 8500,
    discountPrice: 7200,
    stock: 32,
    rating: 4.5,
    reviewCount: 45,
    status: "active",
    image: "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80",
    ],
    description: "A timeless addition to any bathroom, our pedestal wash basin features clean lines and a generous bowl depth. The integrated pedestal elegantly conceals plumbing for a polished, clutter-free look. Made from premium vitreous china with a high-gloss finish that resists staining.",
    specifications: {
      "Material": "Vitreous China",
      "Dimensions": "60 × 48 × 85 cm (with pedestal)",
      "Bowl Depth": "18 cm",
      "Tap Holes": "Single central",
      "Color": "White",
      "Drain": "32mm",
      "Warranty": "3 Years",
    },
    features: ["Concealed plumbing", "Deep basin", "Overflow hole", "Easy clean glaze"],
    isBestSeller: false,
    isFeatured: true,
    reviews: [
      { id: 1, user: "Sunita Rao", rating: 5, date: "2024-11-15", comment: "Beautiful basin! Exactly as described. Great quality." },
      { id: 2, user: "Arun Kumar", rating: 4, date: "2024-10-30", comment: "Good product, nice finish. Arrived well-packed." },
    ]
  },
  {
    id: 5,
    name: "Single Lever Faucet",
    brand: "FlowMaster",
    sku: "ALX-FAU-001",
    category: "Faucets",
    price: 3200,
    discountPrice: 2800,
    stock: 56,
    rating: 4.4,
    reviewCount: 112,
    status: "active",
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80",
    ],
    description: "Precision-engineered for longevity and ease of use, our single lever basin faucet delivers smooth temperature and flow control with a single ergonomic handle. Ceramic disc cartridge ensures drip-free performance for years to come.",
    specifications: {
      "Material": "Brass body, Chrome finish",
      "Cartridge": "Ceramic disc",
      "Flow Rate": "8 L/min",
      "Hot/Cold": "Single lever",
      "Installation": "Single hole",
      "Connection": "3/8\" flexible hose",
      "Warranty": "5 Years",
    },
    features: ["Ceramic disc cartridge", "360° swivel spout", "Anti-splash aerator", "WELS rated"],
    isBestSeller: true,
    isFeatured: false,
    reviews: [
      { id: 1, user: "Deepak Joshi", rating: 5, date: "2024-12-18", comment: "Excellent quality for the price. No dripping and smooth operation." },
      { id: 2, user: "Kavita Singh", rating: 4, date: "2024-12-05", comment: "Good faucet. The chrome finish is very shiny and durable." },
      { id: 3, user: "Ramesh Gupta", rating: 4, date: "2024-11-22", comment: "Works perfectly. Easy installation with the included guide." },
    ]
  },
  {
    id: 6,
    name: "Towel Warmer Rack",
    brand: "LuxHeat",
    sku: "ALX-ACC-001",
    category: "Accessories",
    price: 5800,
    discountPrice: 4999,
    stock: 19,
    rating: 4.3,
    reviewCount: 38,
    status: "active",
    image: "https://images.unsplash.com/photo-1604147706283-d7119b5b822c?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1604147706283-d7119b5b822c?w=600&q=80",
    ],
    description: "Step out of the bath into the warm embrace of a pre-warmed towel. Our electric towel warmer rack adds a touch of hotel-luxury to your home bathroom. Wall-mounted design keeps your towels fluffy, warm, and ready to use while also keeping your bathroom pleasantly heated.",
    specifications: {
      "Power": "60W",
      "Voltage": "220-240V",
      "Bars": "6",
      "Material": "Stainless Steel 304",
      "Finish": "Polished Chrome",
      "Dimensions": "60 × 50 cm",
      "Timer": "Built-in 60-min",
      "Warranty": "2 Years",
    },
    features: ["60W efficient heating", "Built-in timer", "Wall mounted", "Anti-rust coating"],
    isBestSeller: false,
    isFeatured: false,
    reviews: [
      { id: 1, user: "Pooja Reddy", rating: 4, date: "2024-12-08", comment: "Heats up quickly and the build quality is solid. Great addition to our bathroom." },
    ]
  },
  {
    id: 7,
    name: "Corner Shower Enclosure",
    brand: "ClearView",
    sku: "ALX-SHW-002",
    category: "Showers",
    price: 22000,
    discountPrice: 19500,
    stock: 12,
    rating: 4.6,
    reviewCount: 54,
    status: "active",
    image: "https://images.unsplash.com/photo-1620626011761-996317702782?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1620626011761-996317702782?w=600&q=80",
    ],
    description: "Maximise your bathroom space with our elegant corner shower enclosure. Featuring toughened safety glass panels and a smooth sliding door mechanism, this enclosure creates a stunning focal point while maintaining a watertight seal. Perfect for medium to large bathrooms.",
    specifications: {
      "Glass": "8mm Toughened Safety Glass",
      "Frame": "Aluminum alloy",
      "Door Type": "Sliding",
      "Dimensions": "90 × 90 × 195 cm",
      "Finish": "Brushed Silver",
      "Base": "Acrylic tray included",
      "Warranty": "3 Years",
    },
    features: ["8mm toughened glass", "Smooth sliding door", "Adjustable rollers", "Easy clean coating"],
    isBestSeller: false,
    isFeatured: true,
    reviews: [
      { id: 1, user: "Neeraj Malhotra", rating: 5, date: "2024-12-12", comment: "Premium quality enclosure. The glass is thick and the door glides smoothly." },
      { id: 2, user: "Asha Menon", rating: 4, date: "2024-11-29", comment: "Looks very elegant. Professional installation recommended." },
    ]
  },
  {
    id: 8,
    name: "Sensor Faucet",
    brand: "SmartFlow",
    sku: "ALX-FAU-002",
    category: "Faucets",
    price: 6500,
    discountPrice: 5800,
    stock: 28,
    rating: 4.5,
    reviewCount: 73,
    status: "active",
    image: "https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1588854337236-6889d631faa8?w=600&q=80",
    ],
    description: "Touchless technology meets sophisticated design in our sensor faucet. IR sensor detects hand movement within 20cm range, activating water flow instantly — completely hands-free. Ideal for commercial and residential settings where hygiene is paramount.",
    specifications: {
      "Sensor Range": "20 cm",
      "Power": "6V DC (4 × AA)",
      "Flow Rate": "6 L/min",
      "Material": "Brass, Chrome finish",
      "Response Time": "< 0.5s",
      "Auto-shutoff": "Yes (30s)",
      "Warranty": "3 Years",
    },
    features: ["Touchless IR sensor", "Auto shut-off", "Battery powered", "Hygiene+"],
    isBestSeller: true,
    isFeatured: true,
    reviews: [
      { id: 1, user: "Rajan Bose", rating: 5, date: "2024-12-16", comment: "Excellent sensor faucet. Very responsive and saves a lot of water. Modern look too." },
    ]
  },
  {
    id: 9,
    name: "Jacuzzi Bathtub",
    brand: "HydroSpa",
    sku: "ALX-BTH-002",
    category: "Bathtubs",
    price: 95000,
    discountPrice: 88000,
    stock: 4,
    rating: 4.9,
    reviewCount: 32,
    status: "active",
    image: "https://images.unsplash.com/photo-1600566752734-2a0cd6af9176?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1600566752734-2a0cd6af9176?w=600&q=80",
      "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80",
    ],
    description: "The pinnacle of home spa luxury, our Jacuzzi bathtub features 16 hydrotherapy jets strategically placed to target key muscle groups. Built-in LED chromotherapy lighting, a heated backrest, and digital temperature control transform your bathroom into a personal wellness retreat.",
    specifications: {
      "Jets": "16 hydrotherapy jets",
      "Material": "Reinforced Acrylic",
      "Dimensions": "180 × 90 × 65 cm",
      "Pump": "1.5 HP",
      "Voltage": "220V / 50Hz",
      "LED Colors": "7 chromotherapy",
      "Capacity": "350 litres",
      "Warranty": "5 Years",
    },
    features: ["16 hydro jets", "LED chromotherapy", "Heated backrest", "Digital temperature control", "Air bubble system"],
    isBestSeller: false,
    isFeatured: true,
    reviews: [
      { id: 1, user: "Suresh Bhat", rating: 5, date: "2024-12-01", comment: "Absolutely incredible. The jets are powerful and the LED lighting creates a perfect spa ambiance." },
      { id: 2, user: "Lalitha Krishnan", rating: 5, date: "2024-11-15", comment: "Best investment for our home. The whole family loves it." },
    ]
  },
  {
    id: 10,
    name: "Vanity Mirror Cabinet",
    brand: "MirrorLux",
    sku: "ALX-ACC-002",
    category: "Accessories",
    price: 14000,
    discountPrice: 11999,
    stock: 21,
    rating: 4.4,
    reviewCount: 61,
    status: "active",
    image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",
    ],
    description: "Combining storage and style, our vanity mirror cabinet features a full-length illuminated mirror with built-in LED strip lighting and two interior shelves. The anti-fog function ensures clarity even in the steamiest bathrooms, while the sensor dimmer allows you to set your preferred brightness level.",
    specifications: {
      "Dimensions": "60 × 70 × 15 cm",
      "Mirror Type": "Anti-fog LED",
      "Lighting": "6500K cool white LED",
      "Shelves": "2 adjustable",
      "Material": "Aluminum frame",
      "Door": "Soft-close hinges",
      "IP Rating": "IP44",
      "Warranty": "2 Years",
    },
    features: ["LED illumination", "Anti-fog", "Touch dimmer", "Soft-close door", "IP44 rated"],
    isBestSeller: false,
    isFeatured: false,
    reviews: [
      { id: 1, user: "Divya Sharma", rating: 5, date: "2024-12-14", comment: "The LED lighting is perfect for makeup. Anti-fog feature works brilliantly." },
    ]
  },
  {
    id: 11,
    name: "Concealed Cistern",
    brand: "CleanLine",
    sku: "ALX-TOI-002",
    category: "Toilets",
    price: 9000,
    discountPrice: 7800,
    stock: 17,
    rating: 4.3,
    reviewCount: 29,
    status: "active",
    image: "https://images.unsplash.com/photo-1562184647-8f8d21d5264b?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1562184647-8f8d21d5264b?w=600&q=80",
    ],
    description: "Our in-wall concealed cistern is designed for integration with wall-hung toilet systems. The slim-profile tank hides completely within the wall cavity, presenting a sleek, flush-plate front for a minimalist aesthetic. Universal compatibility fits most wall-hung toilet pans.",
    specifications: {
      "Capacity": "6/3 litres (dual flush)",
      "Dimensions": "49 × 36 × 15 cm",
      "Frame Height": "82-112 cm (adjustable)",
      "Material": "Polypropylene",
      "Inlet": "Side or bottom entry",
      "Flush Plate": "Chrome (included)",
      "Warranty": "5 Years",
    },
    features: ["Dual flush 3/6L", "Adjustable frame", "Universal fitting", "Quiet fill"],
    isBestSeller: false,
    isFeatured: false,
    reviews: [
      { id: 1, user: "Gopal Iyer", rating: 4, date: "2024-11-30", comment: "Good quality cistern. Fits perfectly with our wall-hung toilet." },
    ]
  },
  {
    id: 12,
    name: "Soap Dispenser Set",
    brand: "AquaLux Essentials",
    sku: "ALX-ACC-003",
    category: "Accessories",
    price: 1800,
    discountPrice: 1500,
    stock: 87,
    rating: 4.2,
    reviewCount: 95,
    status: "active",
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&q=80",
    ],
    description: "Elevate even the smallest bathroom detail with our premium soap dispenser set. The set includes a countertop liquid soap dispenser and a toothbrush holder, both crafted from heavy resin with a matte ceramic-look finish. Refillable pump mechanism ensures hygienic, easy dispensing.",
    specifications: {
      "Material": "Heavy Resin",
      "Capacity": "300ml",
      "Finish": "Matte White",
      "Set Includes": "Dispenser + Toothbrush holder",
      "Pump Material": "Stainless Steel",
      "Compatible": "Liquid soap, shampoo",
      "Warranty": "1 Year",
    },
    features: ["300ml capacity", "Rust-proof pump", "Non-slip base", "Easy-refill top"],
    isBestSeller: false,
    isFeatured: false,
    reviews: [
      { id: 1, user: "Mamta Desai", rating: 4, date: "2024-12-19", comment: "Looks classy and the pump works smoothly. Great value." },
      { id: 2, user: "Ajay Tiwari", rating: 4, date: "2024-12-03", comment: "Nice set. Quality is good for the price." },
    ]
  },
];

export const CATEGORIES = [
  { id: 1, name: "Bathtubs", icon: "bath", description: "Freestanding, built-in & jacuzzi", status: "active", count: 2 },
  { id: 2, name: "Showers", icon: "shower", description: "Rain showers, enclosures & sets", status: "active", count: 2 },
  { id: 3, name: "Toilets", icon: "toilet", description: "Wall-hung, floor-standing & smart", status: "active", count: 2 },
  { id: 4, name: "Washbasins", icon: "droplets", description: "Pedestal, counter-top & under-mount", status: "active", count: 1 },
  { id: 5, name: "Faucets", icon: "droplet", description: "Single lever, sensor & thermostatic", status: "active", count: 2 },
  { id: 6, name: "Accessories", icon: "package", description: "Towel racks, mirrors & dispensers", status: "active", count: 3 },
];

export const COUPONS = [
  { id: 1, code: "WELCOME10", type: "percent", value: 10, minOrder: 2000, expiry: "2025-12-31", active: true, description: "10% off on first order" },
  { id: 2, code: "FLAT500", type: "flat", value: 500, minOrder: 5000, expiry: "2025-06-30", active: true, description: "Flat ₹500 off on orders above ₹5000" },
  { id: 3, code: "LUXBATH20", type: "percent", value: 20, minOrder: 15000, expiry: "2025-03-31", active: true, description: "20% off on luxury items" },
];

export const DUMMY_CUSTOMERS = [
  { id: 1, name: "Priya Sharma", email: "priya@example.com", phone: "9876543210", orders: 3, spend: 67500, joined: "2024-09-15", status: "active", address: { line1: "12, Rose Garden Apartments", line2: "Koregaon Park", city: "Pune", state: "Maharashtra", pincode: "411001" } },
  { id: 2, name: "Rahul Mehta", email: "rahul@example.com", phone: "9823456789", orders: 1, spend: 42000, joined: "2024-10-22", status: "active", address: { line1: "45, Sector 18", line2: "", city: "Noida", state: "Uttar Pradesh", pincode: "201301" } },
  { id: 3, name: "Anita Kapoor", email: "anita@example.com", phone: "9765432109", orders: 5, spend: 128000, joined: "2024-07-08", status: "active", address: { line1: "8, Bandra West", line2: "Near Turner Road", city: "Mumbai", state: "Maharashtra", pincode: "400050" } },
];

export const DUMMY_ORDERS = [
  {
    id: "ORD-2024-001",
    customerId: 1,
    customerName: "Priya Sharma",
    customerEmail: "priya@example.com",
    customerPhone: "9876543210",
    address: { line1: "12, Rose Garden Apartments", line2: "Koregaon Park", city: "Pune", state: "Maharashtra", pincode: "411001" },
    items: [{ productId: 1, name: "Freestanding Bathtub", price: 42000, qty: 1, image: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&q=80" }],
    subtotal: 42000,
    shipping: 0,
    discount: 0,
    total: 42000,
    paymentMethod: "Razorpay",
    paymentStatus: "Paid",
    razorpayPaymentId: "pay_OaKL1234ABCD",
    orderStatus: "Delivered",
    date: "2024-12-10T10:30:00Z",
    estimatedDelivery: "2024-12-17",
  },
  {
    id: "ORD-2024-002",
    customerId: 2,
    customerName: "Rahul Mehta",
    customerEmail: "rahul@example.com",
    customerPhone: "9823456789",
    address: { line1: "45, Sector 18", line2: "", city: "Noida", state: "Uttar Pradesh", pincode: "201301" },
    items: [
      { productId: 2, name: "Rain Shower Set", price: 10800, qty: 1, image: "https://images.unsplash.com/photo-1600566752734-2a0cd6af9176?w=600&q=80" },
      { productId: 5, name: "Single Lever Faucet", price: 2800, qty: 2, image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&q=80" },
    ],
    subtotal: 16400,
    shipping: 0,
    discount: 500,
    total: 15900,
    paymentMethod: "COD",
    paymentStatus: "COD - Pending",
    razorpayPaymentId: null,
    orderStatus: "Processing",
    date: "2024-12-18T14:15:00Z",
    estimatedDelivery: "2024-12-25",
  },
  {
    id: "ORD-2024-003",
    customerId: 3,
    customerName: "Anita Kapoor",
    customerEmail: "anita@example.com",
    customerPhone: "9765432109",
    address: { line1: "8, Bandra West", line2: "Near Turner Road", city: "Mumbai", state: "Maharashtra", pincode: "400050" },
    items: [{ productId: 9, name: "Jacuzzi Bathtub", price: 88000, qty: 1, image: "https://images.unsplash.com/photo-1600566752734-2a0cd6af9176?w=600&q=80" }],
    subtotal: 88000,
    shipping: 0,
    discount: 0,
    total: 88000,
    paymentMethod: "Razorpay",
    paymentStatus: "Paid",
    razorpayPaymentId: "pay_PbLM5678EFGH",
    orderStatus: "Shipped",
    date: "2024-12-20T09:45:00Z",
    estimatedDelivery: "2024-12-27",
  },
];
